version: "3.8"

services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
